### ISSUE TITLE
max / min width

### ISSUE THREAD

**Issue by fundon** [atom-minimap/minimap#22]

**Comment by bucaran** [comment]
How? I tried unsuccessfully to change the width and failed.

**Comment by fundon** [comment]
@bucaran try this

```css
.minimap {
  max-width: 20%;
  min-width: 50px;
}
```

**Comment by bucaran** [comment]
Thanks! I had already tried that, but it didn't work, that's why I posted here.

Since I have shadow DOM enabled, I also tried

```less
atom-text-editor,
atom-text-editor::shadow {

  .minimap {
    max-width: 10px;
    min-width: 10px;
  }
}
```

to no avail.

**Comment by abe33** [comment]
@bucaran Are you using the v4 preview? If yes the selector to use is a bit different: 

```css
atom-text-editor::shadow  atom-text-editor-minimap {
  width: 10px !important;
}
```

Also make sure you doesn't have the `Adjust Minimap Width To Soft Wrap` enabled (it resizes the minimap programmatically).

**Comment by bucaran** [comment]
Thanks!
```less
atom-text-editor::shadow  atom-text-editor-minimap {
  width: 10px !important;
}
```
Works!
