### ISSUE TITLE
QuickSettings is overlapped by editor scrollbar

### ISSUE THREAD

**Issue by GameplayJDK** [atom-minimap/minimap#279]
So, when I open the QuickSettings (by clicking the little gear in the top right of the minimap) and the scrollbar is visible, the little box that pops up is partially covered by the bar.

I havent't tested this on another OS that linux, but I'd assume it's the same on another system. As this is only another graphical enhancement it should be easy to change.

![screenshot](https://cloud.githubusercontent.com/assets/4069263/6314611/d05fcf20-b9e5-11e4-8e9b-3110177c2d36.png)

**Comment by fundon** [comment]
Thanks for your report. Good catch!

**Comment by fundon** [comment]
Fixed in v4.3.1.

Or you can customize the styles:

```less
minimap-quick-settings {
  position: absolute !important;
  z-index: 5;
}
```
