### ISSUE TITLE
Change pointer to -webkit-grabbing while grabbing visible area

### ISSUE THREAD

**Issue by mnquintana** [atom-minimap/minimap#307]
**Expected:** When you click and drag the visible area in the minimap, the cursor will change from -webkit-grab to -webkit-grabbing.

**Actual:** When you click and drag the visible area in the minimap, the cursor remains -webkit-grab.

**Comment by fundon** [comment]
Good catch!

You can try to add below style to your `styles.less` if you want:
```less
atom-text-editor::shadow atom-text-editor-minimap::shadow .minimap-visible-area {
  &:active {
    cursor: -webkit-grabbing;
  }
}
```
