### ISSUE TITLE
minimap width should be adjustable

### ISSUE THREAD

**Issue by v3ss0n** [atom-minimap/minimap#316]
Right now only charwidth is adjustable and not the width of minimap

**Comment by abe33** [comment]
Hi, do you know that you can change the width of the minimap through CSS?

The only case when the width is defined programatically is when you enable the `Adjust Minimap Width To Soft Wrap` setting.

The following rule cann be used to tweak the minimap width with CSS: 

```less
atom-text-editor::shadow, atom-text-editor {
  atom-text-editor-minimap {
    width: 200px;
  }
}
```

**Comment by v3ss0n** [comment]
I do know but would be nicer as a setting. CSS in styles break from time to time due to depreciations.

**Comment by heroselohim** [comment]
It's the only feature that I personally miss about the minimap. On big screens I would like to make it wider. The CSS tweak is fine by now. Thanks!

**Comment by doersino** [comment]
The CSS rule has no effect on the minimap width for me, independent of the `Adjust Minimap Width To Soft Wrap`setting.

It works when changing it to

```css
atom-text-editor::shadow, atom-text-editor {
  atom-text-editor-minimap {
    width: 200px !important;
  }
}
```

and "Absolute Mode" *and* "On Right" are active.
