### ISSUE TITLE
Minimap hides characters on long lines

### ISSUE THREAD

**Issue by darakian** [atom-minimap/minimap#322]
When I type out a long line of text the minimap seems to hide a character or two.
pic here
http://imgur.com/DyDXwGU

**Comment by abe33** [comment]
This is the intended behavior, the minimap isn't an overlay above the text editor so text won't flow behind it. But the editor will allow you to scroll horizontally (hence the scrollbar at the bottom of the editor).

**Comment by darakian** [comment]
Is there an easy way to change this behavior?

**Comment by abe33** [comment]
Hmm, I think the following rule in your stylesheet should do the trick: 

```less
atom-text-editor::shadow atom-text-editor-minimap {
  position: absolute;
  right: 0;
}
```
At least on my config it works as expected.

I'll consider adding a setting for that given that the solution is simpler that what I thought it'll be at first.
