### ISSUE TITLE
pointer-events: none; for absolute mode

### ISSUE THREAD

**Issue by teddybradford** [atom-minimap/minimap#365]
I think it would be nice to add `pointer-events: none;` to `atom-text-editor-minimap` when absolute mode is enabled so that you are able to click through the minimap container to edit text. To still be able to click on the minimap itself, you can apply `pointer-events: auto;` to the `.minimap-visible-area`.

Here's working CSS that I use in my stylesheet config:

```less
atom-text-editor::shadow atom-text-editor-minimap {
  pointer-events: none;
}

atom-text-editor::shadow atom-text-editor-minimap::shadow .minimap-visible-area {
  pointer-events: auto;
}
```
