### ISSUE TITLE
Minimap (partially) hides when resizing panes

### ISSUE THREAD

**Issue by olmokramer** [atom-minimap/minimap#394]
When I'm resizing panes, the minimap gets partially hidden. This image should explain it better:

![minimap](https://cloud.githubusercontent.com/assets/3612514/10669470/32560856-78e1-11e5-9fc2-256c993bf279.gif)

It seems to be caused by an inline `width` style on the `.lines, .line` in the `atom-text-editor`. When I add the following to my `styles.less` it works just fine:

```less
atom-text-editor::shadow {
  .lines, .line {
    width: 100% !important;
  }
}
```

Should this be fixed in core or in minimap?

/cc @as-cii (you seem to be working a lot on this kind of thing in core)
