### ISSUE TITLE
The instruction of changing the width of minimap in #316 do not work.

### ISSUE THREAD

**Issue by TakayukiKatsuki** [atom-minimap/minimap#428]
I can not change the width of minimap by editing styles.less as below.

atom-text-editor::shadow, atom-text-editor {
  atom-text-editor-minimap {
    width: 200px;
  }
}

Please tell me how to do that.
Also, I do not enable the Adjust Minimap Width To Soft Wrap setting.

**Comment by abe33** [comment]
Hi @TakayukiKatsuki, until recently, the flex-box support was quite buggy, and using the `width` property was still possible, but it's no longer possible. You can use `flex-basis` instead: 

```css
atom-text-editor::shadow, atom-text-editor {
  atom-text-editor-minimap {
    flex-basis: 200px;
  }
}
```
