### ISSUE TITLE
Minimap does not update properly when folding / unfolding code

### ISSUE THREAD

**Issue by forivall** [atom-minimap/minimap#429]
![[gif](http://i.imgur.com/wjnYaNQ.gifv)](http://i.imgur.com/wjnYaNQ.gif)
Can anyone else reproduce this?

My config:
```
  minimap:
    scrollAnimation: true
    scrollAnimationDuration: 100
    charWidth: 0.7
    textOpacity: 0.5
    interline: 0.4
    charHeight: 1.5
    plugins:
      "identifier-highlight": true
      "minimap-autohide": true
      "git-diff": true
      selection: true
      "highlight-selected": true
```
This occurs even if i reset my config, disable all packages other than minimap and set my themes to the defaults, and also on the beta.
OS: Manjaro (Arch) Linux.
