### ISSUE TITLE
[ WISH ]  Show the minimap only in the active pane

### ISSUE THREAD

**Issue by i90rr** [atom-minimap/minimap#441]
Hi,

I'm used to work with multiple panes/frames (like with Emacs) so I very welcome this feature in Atom.
If it possible I would love Minimap sports the option to show only in the active pane - for the sake of saving screen space.

Best.

**Comment by abe33** [comment]
Hi @i90rr, 

You can put the following code in your user stylesheet to achieve that effect: 

```css
atom-text-editor {
  &, &::shadow {
    atom-text-editor-minimap {
      display: none;
    }
  }

  &.is-focused {
    &, &::shadow {
      atom-text-editor-minimap {
        display: block;
      }
    }
  }
}
```
