### ISSUE TITLE
option for pointer-events: none when is abosulte mode

### ISSUE THREAD

**Issue by CosticaPuntaru** [atom-minimap/minimap#444]
Its annoying when you see the code and want to select it or something and the editor scrolls you to some random line that you clicked by mistake.
Maybe an option that will be available only when minimap is in absolute mode that will allow your clicks to pass through minimap?

```css
atom-text-editor-minimap{
  pointer-events: none;
}
```
