### ISSUE TITLE
Minimap content doesn't match pane view

### ISSUE THREAD

**Issue by alexandernst** [atom-minimap/minimap#449]
Screenshot:

![](http://ibin.co/2W21z5mCPoac)

**Comment by abe33** [comment]
I think you just got confused by the fact the minimap has a proportional width (10% of the editor's width), which mean that all the characters on screen may not fit in the available space.

You can tweak the width ratio with CSS such as: 

```css
atom-text-editor::shadow atom-text-editor-minimap:not([stand-alone]), 
atom-text-editor atom-text-editor-minimap:not([stand-alone]) {
  flex-basis: 15%; /* or whatever value you see fit */
}
```
