### ISSUE TITLE
Wrong render in 1.9.0 beta

### ISSUE THREAD

**Issue by hultberg** [atom-minimap/minimap#502]
Hello! I noticed that minimap renders different in Atom 1.9.0. Is this intended?

Atom 1.8.0 | Atom 1.9.0
---------------|---------------
<img width="153" alt="screen shot 2016-06-13 at 21 23 37" src="https://cloud.githubusercontent.com/assets/1257913/16020237/49ab3302-31ad-11e6-9483-1fae2d927cc7.png"> | <img width="165" alt="screen shot 2016-06-13 at 21 23 30" src="https://cloud.githubusercontent.com/assets/1257913/16020255/69320eda-31ad-11e6-97d8-f859f7dd6ae3.png">

Using Mac OSX 10.11.5

**Comment by abe33** [comment]
Hi @hultberg, it is indeed not intended. There were many important changes in 1.9.0 that required to change how we handle things like whitespace characters and line tokens. In most our tests we didn't see anything wrong (I'm always using a version built upon master), maybe that have to do with the editor or the minimap config, could you share with me your config (editor & minimap)?

**Comment by hultberg** [comment]
@abe33 

This is my atom config:
````
"*":
  "advanced-open-file":
    createDirectories: true
  "atom-ctags":
    cmdArgs: "--exclude=*.js"
  core:
    disabledPackages: [
      "symbols-view"
    ]
    excludeVcsIgnoredPaths: false
    themes: [
      "one-dark-ui"
      "atom-material-syntax-dark"
    ]
  docblockr:
    return_description: false
    spacer_between_sections: true
  editor:
    backUpBeforeSaving: true
    invisibles: {}
    lineHeight: 2.2
    scrollPastEnd: true
    tabLength: 4
    tabType: "soft"
  "fuzzy-finder":
    ignoredNames: [
      ".git"
      "svg/"
      "node_modules/"
    ]
  "linter-jshint": {}
  minimap:
    plugins:
      "find-and-replace": true
      "find-and-replaceDecorationsZIndex": 0
      "git-diff": true
      "git-diffDecorationsZIndex": 0
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
      "minimap-hide": true
      "minimap-hideDecorationsZIndex": 0
      pigments: true
      pigmentsDecorationsZIndex: 0
      selection: true
      selectionDecorationsZIndex: 0
  pigments: {}
  "split-diff":
    diffWords: true
    ignoreWhitespace: true
    leftEditorColor: "red"
    rightEditorColor: "green"
  welcome:
    showOnStartup: false
".blade.html.php.text":
  editor:
    commentEnd: " --}}"
    commentStart: "{{-- "
".css.source.twig":
  editor:
    tabLength: 4
".html.text.twig":
  editor:
    tabLength: 4
".js.source.twig":
  editor:
    tabLength: 4
".json.source.twig":
  editor:
    tabLength: 4
".source.twig":
  editor:
    tabLength: 4
".source.twig.yaml":
  editor:
    tabLength: 4
".text.twig.xml":
  editor:
    tabLength: 4
````

Is there a minimap specific config file somewhere?
