### ISSUE TITLE
[Feature Request] Refactor highlights in minimap

### ISSUE THREAD

**Issue by Redsandro** [atom-minimap/minimap#664]
One of my favorite Atom features is that it will mark read- and write occurances of variables and properties. This is supported _out of the box_. **No plugin required.**

Depending on what distro you are using, this is included in the styles by default. Other distros have this disabled. I don't know why, it's a very simple powerful visual aid.

```css
// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow {
  // Read
  .refactor-ref .region {
    background-color: rgba(0, 132, 0, 0.4);
    border-bottom: 2px solid green;
  }
  // Write
  .refactor-mut .region {
    background-color: rgba(192, 0, 0, 0.4);
    border-bottom: 2px solid red;
  }
  // New
  .refactor-decl .region {
    background-color: rgba(132, 132, 0, 0.4);
    border-bottom: 2px solid orange;
  }
}
```

__Result:__

![image](https://user-images.githubusercontent.com/1702193/39131175-1f49607e-470f-11e8-9f0d-343989c4bde0.png)

As you can see, these are not visible in the minimap.
