### ISSUE TITLE
Scroll bar position when toggling minimap off

### ISSUE THREAD

**Issue by gilbertohasnofb** [atom-minimap/minimap#708]
When Minimap is toggled on (absolute mode disabled, right-hand side), the scroll bar of the text below it is placed to its left:

![Screenshot from 2020-10-07 16-20-02](https://user-images.githubusercontent.com/5700795/95351748-792e9500-08b9-11eb-9683-6e12826f825f.png)

Toggling Minimap off with `minimap:toggle` will simply remove Minimap, but leave the space behind it:

![Screenshot from 2020-10-07 16-20-12](https://user-images.githubusercontent.com/5700795/95351771-7af85880-08b9-11eb-84fe-00aacda8bda3.png)

Disabling the package altogether will move the scroll bar to where it would be normally placed:

![Screenshot from 2020-10-07 16-20-33](https://user-images.githubusercontent.com/5700795/95351802-7cc21c00-08b9-11eb-9922-5df39f0294d0.png)

My suggestion on how to tackle this: either move the scroll bar to the right hand side of minimap (regardless of absolute mode), or alternatively move it there at least when minimap is toggled off.

**Comment by kireerik** [comment]
@gilbertohasnofb I have created some custom styles to place the scroll bar to it's original place while this package is enabled. I can share it here if you are interested.

**Comment by gilbertohasnofb** [comment]
@kireerik Yes, that would be great, thank you so much!

**Comment by kireerik** [comment]
I have also made it narrower. So you may meed to adjust the code if you would like to use the default width:
```less
atom-text-editor atom-text-editor-minimap {
	max-width: 5.74vw;
	right: calc(.5px + 4px + 5px);
}
atom-text-editor[with-minimap] > div {
	contain: size layout !important;
	overflow: visible !important;
}
atom-text-editor[with-minimap] > div .scroll-view {
	contain: size layout !important;
	overflow: visible !important;
}
atom-text-editor[with-minimap] > div .scroll-view .vertical-scrollbar {
	right: -5.74vw !important;
}
```

**Comment by kireerik** [comment]
As a bonus with these styles the visible area indicator behaves as it does in Sublime Text if you need this as well:
```less
atom-text-editor atom-text-editor-minimap .minimap-visible-area::after {
	opacity: 0;
	transition: all .3s ease-out;
}
atom-text-editor atom-text-editor-minimap:hover .minimap-visible-area::after {
	opacity: 1;
	transition: all .05s ease-in;
}
```
