### ISSUE TITLE
Hot style preview in user stylesheet without reloading Atom

### ISSUE THREAD

**Issue by UziTech** [atom-minimap/minimap#784]
It doesn't work to change the color in atom stylesheet.

```css
.minimap .cursor-line {
  background: green;
}
```

related https://github.com/atom-minimap/minimap-cursorline/issues/35
